# base configuration for each component of the pipeline

preprocessing_and_training:
  root_dir: artifacts/preprocessing_and_training
  model: artifacts/preprocessing_and_training/model.joblib
  train_data_dir: artifacts/preprocessing_and_training/train_data
  test_data_dir: artifacts/preprocessing_and_training/test_data
  best_params: artifacts/preprocessing_and_training/best_params.json

model_evaluation:
  root_dir: artifacts/model_evaluation
  model: artifacts/preprocessing_and_training/model.joblib
  train_data_dir: artifacts/preprocessing_and_training/train_data
  test_data_dir: artifacts/preprocessing_and_training/test_data
  scores: artifacts/model_evaluation/scores.json
  forecast_vs_actual_plot: artifacts/model_evaluation/forecast_vs_actual.png

forecasting:
  root_dir: artifacts/forecasting
  train_data_dir: artifacts/preprocessing_and_training/train_data
  test_data_dir: artifacts/preprocessing_and_training/test_data
  model: artifacts/preprocessing_and_training/model.joblib
  forecast_plot: artifacts/forecasting/forecast.png
  forecast_data: artifacts/forecasting/forecast_data.csv