data_analysis:
  root_dir: artifacts/data_analysis
  data_summary: artifacts/data_analysis/data_summary.json

preprocessing_and_training:
  root_dir: artifacts/preprocessing_and_training
  data_summary: artifacts/data_analysis/data_summary.json
  model: artifacts/preprocessing_and_training/model.joblib
  test_data_dir: artifacts/processing_and_training/test_data
  best_params: artifacts/preprocessing_and_training/best_params.json

model_evaluation:
  root_dir: artifacts/model_evaluation
  model: artifacts/preprocessing_and_training/model.joblib
  test_data_dir: artifacts/model_evaluation/test_data
  scores: artifacts/model_evaluation/scores.json
  forecast_vs_actual_plot: artifacts/model_evaluation/forecast_vs_actual.png

forecasting:
  root_dir: artifacts/forecasting
  model: artifacts/preprocessing_and_training/model.joblib
  forecast_plot: artifacts/forecasting/forecast.png