# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - autoforecast

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://autoforecast.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_85b7278f852540ab894cd5244b384a71 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a517ba521ef24df3a4881294a6a918b4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: autoforecast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85b7278f852540ab894cd5244b384a71 }}/autoforecast/autoforecast:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'autoforecast'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_434704e71b474b8ea2fa9fe005877eea }}
        images: 'autoforecast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_85b7278f852540ab894cd5244b384a71 }}/autoforecast/autoforecast:${{ github.sha }}'